#!/bin/bash

echo "🔧 CONFIGURACIÓN DE GOOGLE CLOUD CONSOLE"
echo "========================================"
echo ""
echo "Para que funcione la autenticación con Google Calendar, debes:"
echo ""
echo "1. Ve a Google Cloud Console: https://console.cloud.google.com/"
echo "2. Selecciona tu proyecto o crea uno nuevo"
echo "3. Ve a 'APIs & Services' > 'Credentials'"
echo "4. Encuentra tu OAuth 2.0 Client ID: 608223216812-ecbl9q2t6689a16bjbpkpcglq5rpb33v.apps.googleusercontent.com"
echo "5. Haz clic en 'Edit' (ícono de lápiz)"
echo "6. En 'Authorized redirect URIs', agrega:"
echo "   http://localhost:3001/api/auth/google/callback"
echo "7. Guarda los cambios"
echo ""
echo "💡 IMPORTANTE: Las URIs de redirección deben coincidir exactamente"
echo "   - URI actual en .env.local: http://localhost:3001/api/auth/google/callback"
echo "   - Esta URI debe estar en Google Cloud Console"
echo ""
echo "8. También verifica que estas APIs estén habilitadas:"
echo "   - Google Calendar API"
echo "   - Google People API (para información del usuario)"
echo ""
echo "Una vez hecho esto, el botón 'Conectar Google Calendar' funcionará."
echo ""
